// GENERATED by tools/build-slot.mjs — do not edit by hand.
// A module rather than JSON so the build tools and the app can both import
// it without JSON import attributes.
export default {
  "_comment": "Measured from pillar_slots.glb by tools/build-slot.mjs. Pillar axis at origin, base at Y=0, front machine faces +X.",
  "lever": {
    "pivot": [
      0.73081,
      1.08532,
      -0.29767
    ],
    "axis": "z",
    "knob": {
      "center": [
        0.80006,
        1.40967,
        -0.31999
      ],
      "radius": 0.032
    },
    "knobLocal": [
      0.06925,
      0.32435,
      -0.02233
    ],
    "armLength": 0.33166
  },
  "stool": {
    "origin": [
      1.54346,
      0,
      -0.00892
    ],
    "seatCenter": [
      1.54346,
      0.80275,
      -0.00892
    ],
    "seatRadius": 0.19892
  },
  "reels": [
    {
      "center": [
        0.82301,
        1.28021,
        -0.10905
      ],
      "radius": 0.10046,
      "width": 0.10343
    },
    {
      "center": [
        0.82301,
        1.28021,
        0.00284
      ],
      "radius": 0.10046,
      "width": 0.10343
    },
    {
      "center": [
        0.82301,
        1.28021,
        0.11484
      ],
      "radius": 0.10046,
      "width": 0.10343
    }
  ],
  "bounds": {
    "min": [
      -1.8268,
      0,
      -1.8267
    ],
    "max": [
      1.8268,
      2.0031,
      1.8267
    ]
  }
};
